version: '3.8'
services:
  proxy:
    image: colinmollenhour/haproxy-service:2.6-alpine
    restart: unless-stopped
    environment:
      - SERVICE_HOSTNAME=cache
    ports:
      - 6379:6379
    volumes:
      - ./redis.cfg.tpl:/etc/haproxy.cfg.tpl:ro
    depends_on:
      - cache
    
  cache:
    image: redis:7-alpine
    scale: 2
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning

